# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-deploy
  type: LoadBalancer ## currently set for testing only . never expose a service. set it ClusterIp and expose a reverse proxy to the public not the backend service itselfe
  ports:
    - name: notify-service
      protocol: "TCP"
      port: 8084
      targetPort: 8084
---
